travis:
  secure:
    BINSTAR_TOKEN: TZ1d7UKheXHqgbiK1+x6GhYlwJ9cb1k3YrsvliGropbpTxL2pdluUkCVsEkiiclQxetjgAfGEMj1LUO/B2SD8k/gQaE/3/+YVmQrtVbnHJZxK1fw0JcZVrsoj92kpkfWBhrzScj09b6HP6nBRUZonSL72qS0RfxUYpD4dEwdGkABaNvShtKvXDcjS50q7fX73QxZvc1UX7o/sPTBjpodiSG/NL5y/tmU9H5svT4i6NkOobmm0p6lA/q+H+0KrOEHJnsTq78lScycIlkrFrnnY4TpctKzVVBg98E1EyzWTeM/NQJXFsxgwSCuM3Da6vxAQU0RLgN5CDR7kG9olMWa5k/7TuBia3YTmO0gaoMx3nzmqRCBEY/KMmAaN2pwse0SILjUfzsWfbMGLh8Uwwfl/Kbc6lve8orTs8y5lDy2KDU7I/EL1xmnIABzWbp6PxazfQEdGFMfzpSb9JCeWhdkbnNcYvDdIv062zrIiYdD5Z8fcWi8hChTYlam1J28MKf1/lFsxfEyRBDxTR0JaTl+zhuUqMHlTxFfcBZYaih6goQdnHJLoDa9r/DsSnzeXPnMpOhGIgd6x8d6mbAbpNaImsPSMW/yl1YQFcc+ongr2EJcV757Ud/XjWydtz/2SFimzdgv2xneC4BCGl2iZtY/yn+meC9xQl9Ts+tICJp/5dY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
