travis:
  secure:
    BINSTAR_TOKEN: DSUVpwhyAtjIqQXGkCo5qkT5ATg+Wa4NZveWr7J4uYr4sKC6PWUM43+rpKY8B7U+C3oOjxGR30peqq4NFFINNzyHPemOjcpXkIMKCgplkQfXoDqvQDF+k5RYlbS6umSjPo26fLS+uqGny+AiBwBSOXV6MkgU158OjvKnuzHlSy+oHqPNpEIOWemWB3KDMXf+UoYaPV4P9oPEUI1blVEQHs/+yY3mXbiJyhDN0BUR0WCWzXhWLlw/hHMFxtC8sc4Ncpl0H45m420HUfr0wPZNztYhBzCBjsulnSZ256wSAWGIfghhAEFhIOvEElzWEqMrEBAS/DUEH2b9MeA4SC6fuLWYRe1W5RKshXVNm36JsetkjkkjENXbAVQYQtJYHd1CNBgW4Kk1eaQYaqXUMjEZkTZYf17RImGp1fCL+CTUH8sXVPKOQk/OX5o3E3S63FY0YR7BQ9PyP/bEqPTEIdMdCgRh+vp7czlZQZEVdeVSrnAgCABQUUtcxFHrvC0lphPRH4mASj0yBoVcHN3Umjlxt4v3eQnNbxhtRwHvincyiAiUpGmIDbwSTvtAwLo2K1jaCYk5XXUQXM5Sxtg2VUx3gakSf2lHSSNsT6Sfm8x4uqRdrB22tt8eh1hMccmXkYAGR8PHAJ4zZt51msJ61dsS8WxQV5KG9OYDj1Jez4PVHVw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
